"""
Output generators:
  - n8n importable JSON workflows
  - Antigravity / Claude Code prompts
  - Coolify deploy commands
  - Supabase schema SQL
"""
import json
import uuid
from datetime import datetime


# ─── n8n JSON Generator ──────────────────────────────────────────────────────

def generate_n8n_json(business_name: str, industry: str, agents: list, n8n_url: str = "") -> str:
    """Generate a basic importable n8n workflow JSON scaffold."""
    nodes = [
        {
            "id": str(uuid.uuid4()),
            "name": "Webhook Trigger",
            "type": "n8n-nodes-base.webhook",
            "typeVersion": 1,
            "position": [240, 300],
            "parameters": {
                "path": f"{industry.lower().replace(' ', '-')}-agent",
                "responseMode": "responseNode",
            }
        },
        {
            "id": str(uuid.uuid4()),
            "name": "AI Agent Router",
            "type": "@n8n/n8n-nodes-langchain.agent",
            "typeVersion": 1,
            "position": [480, 300],
            "parameters": {
                "systemMessage": f"You are an AI agent for {business_name} in the {industry} sector. Route incoming requests to the correct automation workflow. Available agents: {', '.join(agents[:5])}",
                "options": {}
            }
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Supabase - Log Interaction",
            "type": "n8n-nodes-base.supabase",
            "typeVersion": 1,
            "position": [720, 300],
            "parameters": {
                "operation": "insert",
                "tableId": "interactions",
                "dataToSend": "autoMapInputData",
            }
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Respond to Webhook",
            "type": "n8n-nodes-base.respondToWebhook",
            "typeVersion": 1,
            "position": [960, 300],
            "parameters": {
                "respondWith": "json",
                "responseBody": "={{ {status: 'ok', agent: $json.output} }}"
            }
        }
    ]

    # Add agent-specific nodes
    for i, agent in enumerate(agents[:3]):
        nodes.append({
            "id": str(uuid.uuid4()),
            "name": f"Agent: {agent[:30]}",
            "type": "@n8n/n8n-nodes-langchain.chainLlm",
            "typeVersion": 1,
            "position": [480, 480 + (i * 120)],
            "parameters": {
                "prompt": f"Execute the following task for {business_name}: {agent}. Use all available tools and return a structured response.",
            }
        })

    workflow = {
        "name": f"{business_name} — Agentic AI System",
        "nodes": nodes,
        "connections": {
            "Webhook Trigger": {"main": [[{"node": "AI Agent Router", "type": "main", "index": 0}]]},
            "AI Agent Router": {"main": [[{"node": "Supabase - Log Interaction", "type": "main", "index": 0}]]},
            "Supabase - Log Interaction": {"main": [[{"node": "Respond to Webhook", "type": "main", "index": 0}]]},
        },
        "active": False,
        "settings": {
            "executionOrder": "v1",
            "saveManualExecutions": True,
            "callerPolicy": "workflowsFromSameOwner",
        },
        "tags": [industry, "agentic", "adam-system-builder"],
        "meta": {
            "templateCredsSetupCompleted": False,
            "generatedBy": "Adam's System Builder",
            "generatedAt": datetime.utcnow().isoformat(),
            "businessName": business_name,
            "industry": industry,
        }
    }
    return json.dumps(workflow, indent=2)


# ─── Antigravity / Claude Code Prompt ────────────────────────────────────────

def generate_antigravity_prompt(business_name: str, industry: str, agents: list,
                                 tech_stack: list, requirements: str = "", goal: str = "") -> str:
    agents_str = "\n".join([f"  {i+1}. {a}" for i, a in enumerate(agents)])
    stack_str = ", ".join(tech_stack)

    return f"""# Build Prompt — {business_name} Agentic AI System
# Generated by Adam's System Builder | {datetime.utcnow().strftime('%Y-%m-%d')}

## Mission
You are an expert n8n Senior Developer and Agentic AI Systems Architect.
Build a complete, production-ready agentic AI system for **{business_name}** in the **{industry}** sector.

## Tech Stack
{stack_str}
- Self-hosted on Hostinger VPS via Coolify
- n8n for workflow orchestration
- Supabase for database + auth + storage
- Claude Code / Antigravity for autonomous agent execution
- Code Rabbit CLI for automated bug fixing + PR reviews

## Agents to Build
{agents_str}

## Requirements
{requirements or 'See industry playbook defaults.'}

## Primary Goal
{goal or f'Create a fully autonomous AI system that handles the top 3 agent workflows for {business_name} with minimal human intervention.'}

## Deliverables Required
1. **n8n Workflow JSON** — importable, production-ready, all nodes connected
2. **Supabase Schema SQL** — tables, RLS policies, indexes
3. **Coolify Deploy Commands** — exact commands to deploy to Hostinger
4. **Environment Variables List** — all .env vars needed
5. **Agent System Prompts** — optimised prompts for each AI node
6. **Testing Checklist** — how to verify each agent works

## Constraints
- Self-hosted only — no cloud-lock tools
- All secrets via environment variables (never hardcoded)
- Every workflow must have error handling + alerting
- Code Rabbit must review every generated code file
- Follow Cook OS model: Skills + Context + Tools

## Code Rabbit Integration
After generating each file, run:
```bash
coderabbit review --file [filename] --fix-auto
```

## Style Guide
- n8n nodes: use descriptive names, group by function
- Supabase: snake_case tables, uuid primary keys, created_at/updated_at on all tables
- Error nodes: always route to a Slack/Discord webhook for alerting
- All webhook URLs: use descriptive paths (/{industry.lower().replace(' ','-')}/agent-name)

Build it. Make it autonomous. Make it fast to deploy.
"""


# ─── Coolify Deploy Commands ──────────────────────────────────────────────────

def generate_coolify_commands(business_name: str, coolify_url: str = "",
                               coolify_token: str = "", domain: str = "") -> str:
    slug = business_name.lower().replace(" ", "-").replace("/", "-")
    return f"""# Coolify Deploy Commands — {business_name}
# Generated by Adam's System Builder

# ─── 1. Connect to your Hostinger VPS ───────────────────────────────────────
ssh root@{domain or 'YOUR_VPS_IP'}

# ─── 2. Install Coolify (if not already installed) ───────────────────────────
curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash

# ─── 3. Deploy n8n via Coolify CLI or dashboard ──────────────────────────────
# Option A: Via Coolify Dashboard (recommended)
# 1. Open https://{domain or 'YOUR_VPS_IP'}:8000
# 2. New Resource → Docker Compose
# 3. Paste the docker-compose.yml generated below
# 4. Set all environment variables in the Coolify UI
# 5. Click Deploy

# Option B: Via API
curl -X POST "{coolify_url or 'https://YOUR_COOLIFY_URL'}/api/v1/deploy" \\
  -H "Authorization: Bearer {coolify_token or 'YOUR_COOLIFY_TOKEN'}" \\
  -H "Content-Type: application/json" \\
  -d '{{"uuid": "{slug}-n8n"}}'

# ─── 4. n8n docker-compose.yml ───────────────────────────────────────────────
cat > docker-compose-{slug}.yml << 'EOF'
version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${{N8N_HOST}}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://{domain or 'YOUR_DOMAIN'}/
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${{N8N_USER}}
      - N8N_BASIC_AUTH_PASSWORD=${{N8N_PASSWORD}}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${{SUPABASE_HOST}}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=${{SUPABASE_USER}}
      - DB_POSTGRESDB_PASSWORD=${{SUPABASE_PASSWORD}}
      - N8N_ENCRYPTION_KEY=${{N8N_ENCRYPTION_KEY}}
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
EOF

# ─── 5. Import your generated workflow ───────────────────────────────────────
# After n8n is running, import via UI or CLI:
# Dashboard → Workflows → Import from file → select {slug}-workflow.json

# ─── 6. Verify deployment ─────────────────────────────────────────────────────
curl https://{domain or 'YOUR_DOMAIN'}/healthz
# Expected: {{"status":"ok"}}
"""


# ─── Supabase Schema SQL ──────────────────────────────────────────────────────

def generate_supabase_sql(business_name: str, industry: str) -> str:
    slug = industry.lower().replace(" ", "_").replace("/", "_")
    return f"""-- Supabase Schema — {business_name}
-- Generated by Adam's System Builder

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ─── Projects Table ────────────────────────────────────────────────────────
create table if not exists projects (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  industry text,
  business_type text,
  status text default 'active',
  config jsonb default '{{}}',
  owner text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ─── Interactions / Agent Logs ─────────────────────────────────────────────
create table if not exists interactions (
  id uuid default uuid_generate_v4() primary key,
  project_id uuid references projects(id) on delete cascade,
  agent_name text,
  input jsonb,
  output jsonb,
  status text default 'pending',
  duration_ms int,
  error text,
  created_at timestamptz default now()
);

-- ─── Settings ──────────────────────────────────────────────────────────────
create table if not exists settings (
  key text primary key,
  value text,
  updated_at timestamptz default now()
);

-- ─── Industry-specific: {industry} ────────────────────────────────────────
create table if not exists {slug}_clients (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  email text,
  phone text,
  metadata jsonb default '{{}}',
  created_at timestamptz default now()
);

-- ─── RLS Policies ──────────────────────────────────────────────────────────
alter table projects enable row level security;
alter table interactions enable row level security;
alter table settings enable row level security;

-- Service role has full access (used by n8n + backend)
create policy "Service role access" on projects for all using (true);
create policy "Service role access" on interactions for all using (true);
create policy "Service role access" on settings for all using (true);

-- ─── Indexes ───────────────────────────────────────────────────────────────
create index if not exists idx_interactions_project on interactions(project_id);
create index if not exists idx_interactions_created on interactions(created_at desc);
create index if not exists idx_projects_owner on projects(owner);

-- ─── Auto-update timestamps ────────────────────────────────────────────────
create or replace function update_updated_at()
returns trigger as $$ begin new.updated_at = now(); return new; end; $$ language plpgsql;

create trigger projects_updated_at before update on projects
  for each row execute procedure update_updated_at();
"""
