"""
Industry playbooks — the brain of Adam's System Builder.
Each playbook = Skills + Context + Tools (Cook OS model).
"""

PLAYBOOKS = {
    "Catholic Archdiocese / Nonprofit": {
        "icon": "✝️",
        "tag": "archdiocese",
        "description": "98 parishes, 146 schools, 190 social service sites. 16,000+ staff.",
        "common_agents": [
            "IT Ticket Auto-Triage + Root Cause Analysis",
            "Azure Infrastructure Monitoring Agent",
            "Documentation Auto-Generator (diagrams, KB articles, flowcharts)",
            "Veeam Backup Orchestration + DR Runbook",
            "Entra ID / Active Directory Sync Monitor",
            "On-Call Roster + SMS/Voice Escalation Agent",
            "Donation Flow Automation + Receipt Generator",
            "Parish Event Booking + Mass Schedule Automation",
            "Community Comms (Email/WhatsApp/SMS broadcast)",
            "Grant & Compliance Reporting Automation",
        ],
        "questions": [
            {"label": "Automate IT ticket routing & root-cause analysis?", "type": "checkbox"},
            {"label": "Auto-generate system documentation & KB articles?", "type": "checkbox"},
            {"label": "Azure migration monitoring & alerting?", "type": "checkbox"},
            {"label": "Veeam/backup orchestration + DR workflows?", "type": "checkbox"},
            {"label": "On-call escalation via SMS/voice?", "type": "checkbox"},
            {"label": "Parish donation flows + receipt automation?", "type": "checkbox"},
            {"label": "Event/Mass schedule automation?", "type": "checkbox"},
            {"label": "Number of staff / sites in scope", "type": "text"},
            {"label": "Current helpdesk platform (e.g. ServiceNow, Jira)", "type": "text"},
            {"label": "Azure subscription tier (if known)", "type": "text"},
            {"label": "Any HIPAA / compliance requirements?", "type": "checkbox"},
            {"label": "Integration with existing Microsoft 365?", "type": "checkbox"},
        ],
        "tech_stack": ["n8n", "Azure Monitor", "Entra ID", "Veeam API", "Supabase", "Coolify"],
        "n8n_templates": [
            "IT Ticket → AI Triage → Assign → Notify",
            "Azure Alert → Root Cause AI → Slack/Teams → Auto-Resolve",
            "Backup Job → Status Check → DR Report → Email",
        ],
        "default_hosting": "Hostinger VPS (customer-owned)",
    },

    "SaaS": {
        "icon": "🚀",
        "tag": "saas",
        "description": "B2B or B2C SaaS product — growth, automation, and retention agents.",
        "common_agents": [
            "Lead Scoring + CRM Auto-Enrichment",
            "Onboarding Email Sequence (AI-personalised)",
            "Churn Prediction + Proactive Outreach Agent",
            "Support Ticket → AI Draft → Human Review",
            "Product Analytics → Weekly CEO Digest",
            "Trial-to-Paid Conversion Nudge Agent",
            "Bug Report → Code Rabbit Fix → PR → Deploy",
            "Invoice & Dunning Automation (Stripe)",
            "Competitor Monitoring Agent",
            "Affiliate / Partner Tracking Automation",
        ],
        "questions": [
            {"label": "B2B or B2C?", "type": "select", "options": ["B2B", "B2C", "Both"]},
            {"label": "Current CRM (HubSpot, Salesforce, Pipedrive, etc.)", "type": "text"},
            {"label": "Payment gateway (Stripe, Paddle, etc.)", "type": "text"},
            {"label": "Monthly active users (approx)", "type": "text"},
            {"label": "Support volume (tickets/month)", "type": "text"},
            {"label": "Churn reduction is a priority?", "type": "checkbox"},
            {"label": "Auto-fix code bugs via Code Rabbit + Claude?", "type": "checkbox"},
            {"label": "Voice agent for sales calls?", "type": "checkbox"},
            {"label": "Outbound email automation needed?", "type": "checkbox"},
        ],
        "tech_stack": ["n8n", "Stripe", "HubSpot", "Supabase", "Code Rabbit", "Claude Code"],
        "n8n_templates": [
            "New Lead → Score → CRM → Personalised Email Sequence",
            "Trial Signup → Onboarding Drip → Convert Nudge",
            "Bug Report → Code Rabbit CLI → Fix → GitHub PR",
        ],
        "default_hosting": "Hostinger VPS",
    },

    "Healthcare": {
        "icon": "🏥",
        "tag": "healthcare",
        "description": "Clinics, hospitals, allied health — compliance-first automation.",
        "common_agents": [
            "Patient Appointment Reminder (SMS/Voice)",
            "Referral Intake & Triage Automation",
            "After-Hours Voice Agent (FAQ + booking)",
            "Clinical Notes → Structured Summary AI",
            "Billing & Medicare Claim Automation",
            "Staff Roster + On-Call SMS Alerts",
            "Medication Refill Request Handler",
            "Patient Feedback Collection + Analysis",
            "GP Letter Auto-Generation",
            "Compliance Audit Trail Automation",
        ],
        "questions": [
            {"label": "HIPAA / Australian Privacy Act compliance required?", "type": "checkbox"},
            {"label": "Practice type (GP, Specialist, Allied Health, Hospital)", "type": "text"},
            {"label": "Current PMS (Best Practice, MedicalDirector, etc.)", "type": "text"},
            {"label": "Telehealth integration needed?", "type": "checkbox"},
            {"label": "Voice agent for after-hours calls?", "type": "checkbox"},
            {"label": "Appointment reminders via SMS?", "type": "checkbox"},
            {"label": "Medicare / billing automation?", "type": "checkbox"},
            {"label": "Number of practitioners", "type": "text"},
            {"label": "Patient volume per day (approx)", "type": "text"},
        ],
        "tech_stack": ["n8n", "Twilio", "ElevenLabs", "Supabase (encrypted)", "HL7 FHIR"],
        "n8n_templates": [
            "Booking Confirmed → 24h SMS Reminder → Confirmation → No-show follow-up",
            "After-hours call → Voice AI → FAQ or Book → Handoff",
            "Clinical note → GPT Summary → PMS update",
        ],
        "default_hosting": "Hostinger VPS (Australian data centre)",
    },

    "E-commerce": {
        "icon": "🛒",
        "tag": "ecommerce",
        "description": "Shopify / WooCommerce / custom — sell more, automate everything.",
        "common_agents": [
            "Abandoned Cart Recovery (Email + SMS + Voice)",
            "Post-Purchase Upsell Flow",
            "Inventory Low-Stock Alert + Reorder PO",
            "Customer Review Harvesting + Response",
            "Returns & Refunds Automation",
            "Influencer / Affiliate Outreach Agent",
            "Dynamic Pricing Monitor (competitor scrape)",
            "Loyalty Points + VIP Tier Automation",
            "New Product Launch Campaign Sequence",
            "Fraud Detection Alert + Manual Review Trigger",
        ],
        "questions": [
            {"label": "Platform (Shopify, WooCommerce, Custom)", "type": "select", "options": ["Shopify", "WooCommerce", "Custom", "Other"]},
            {"label": "Monthly orders (approx)", "type": "text"},
            {"label": "Abandoned cart recovery needed?", "type": "checkbox"},
            {"label": "Voice agent for order status / support?", "type": "checkbox"},
            {"label": "Inventory management automation?", "type": "checkbox"},
            {"label": "Loyalty program automation?", "type": "checkbox"},
            {"label": "Influencer / affiliate tracking?", "type": "checkbox"},
            {"label": "Current ESP (Klaviyo, Mailchimp, etc.)", "type": "text"},
        ],
        "tech_stack": ["n8n", "Shopify API", "Klaviyo", "Twilio", "Supabase"],
        "n8n_templates": [
            "Abandoned cart (1h) → Email 1 → (24h) → SMS → (72h) → Discount offer",
            "Order shipped → Tracking update → Review request (7d) → Upsell",
            "Inventory < threshold → Reorder PO → Supplier email → Update sheet",
        ],
        "default_hosting": "Hostinger VPS",
    },

    "Education": {
        "icon": "🎓",
        "tag": "education",
        "description": "Schools, RTOs, online courses — enrolment to graduation automation.",
        "common_agents": [
            "Student Enrolment + Onboarding Automation",
            "Course Completion Nudge Agent",
            "Parent Communication Broadcast",
            "Assessment Submission Tracker + Reminders",
            "Teacher Substitution Roster Agent",
            "Compliance Reporting (ASQA / ACARA)",
            "Alumni Engagement + Fundraising Agent",
            "AI Tutoring FAQ Agent (RAG on curriculum)",
            "Fee Payment Reminder + Overdue Escalation",
            "Event + Excursion Management Automation",
        ],
        "questions": [
            {"label": "Institution type (School, RTO, University, Online Course)", "type": "text"},
            {"label": "Number of students", "type": "text"},
            {"label": "Current LMS (Canvas, Moodle, etc.)", "type": "text"},
            {"label": "Compliance reporting required (ASQA, ACARA)?", "type": "checkbox"},
            {"label": "Parent SMS/email notifications needed?", "type": "checkbox"},
            {"label": "AI tutoring / FAQ chatbot needed?", "type": "checkbox"},
            {"label": "Fee payment automation?", "type": "checkbox"},
        ],
        "tech_stack": ["n8n", "Supabase", "Twilio", "OpenAI/Claude", "Moodle API"],
        "n8n_templates": [
            "Enrolment form → Create account → Welcome sequence → Onboarding checklist",
            "Assignment due in 48h → Student reminder → Missed → Escalate to teacher",
            "Parent query → AI FAQ → Resolved or → Human handoff",
        ],
        "default_hosting": "Hostinger VPS",
    },

    "Real Estate": {
        "icon": "🏡",
        "tag": "realestate",
        "description": "Agencies, property managers, developers — list faster, convert more.",
        "common_agents": [
            "Lead Capture + Instant Follow-up Voice/SMS",
            "Property Listing Auto-Generator (photos → copy)",
            "Open Home Registration + Follow-up Sequence",
            "Rental Maintenance Request Handler",
            "Lease Renewal Reminder + Auto-Send",
            "Market Report Generation (weekly digest)",
            "Vendor Report Auto-Compilation",
            "Buyer Matching Agent (new listings → matched leads)",
        ],
        "questions": [
            {"label": "Agency type (Sales, PM, Development, All)", "type": "text"},
            {"label": "Current CRM (Rex, VaultRE, Salesforce, etc.)", "type": "text"},
            {"label": "Number of properties under management", "type": "text"},
            {"label": "Instant lead response via voice/SMS?", "type": "checkbox"},
            {"label": "Rental maintenance automation?", "type": "checkbox"},
            {"label": "AI property description generator?", "type": "checkbox"},
        ],
        "tech_stack": ["n8n", "Twilio", "ElevenLabs", "Supabase", "REI API"],
        "n8n_templates": [
            "Lead form → Instant SMS/call → CRM create → Agent notify",
            "New listing → Match buyers → Personalised email + SMS",
            "Maintenance request → Tradesperson book → Tenant update",
        ],
        "default_hosting": "Hostinger VPS",
    },
}

def get_playbook(industry: str) -> dict:
    return PLAYBOOKS.get(industry, {
        "icon": "🔧",
        "tag": "custom",
        "description": "Custom build — fill in the requirements below.",
        "common_agents": [],
        "questions": [{"label": "Paste full requirements or brief here", "type": "textarea"}],
        "tech_stack": ["n8n", "Supabase", "Coolify"],
        "n8n_templates": [],
        "default_hosting": "Hostinger VPS",
    })

def list_industries():
    return list(PLAYBOOKS.keys()) + ["Other / Custom"]
